### ISSUE TITLE
Give proper exception when Python file is missing

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/knime-python-wrapper#1]
Instead of 

```
java.lang.NullPointerException
    at java.io.Reader.<init>(Reader.java:78)
    at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
    at nl.esciencecenter.e3dchem.python.PythonWrapperNodeModel.getPythonCode(PythonWrapperNodeModel.java:127)
```

In the getPythonCode() method check if Python script file can be read, if not throw a IOException.

**Comment by sverhoeven** [comment]
A FileNotFoundException is now thrown
